#!/bin/bash

# This script helps to sync (rebase) 
# enterprise release branch with corresponding release branch.

usage()
{
	echo "Usage: $0 <repo name> <community release branch>"
	echo " Example: $0 maya v1.10.x"
	exit 1
}

if [ $# -ne 2 ]; then
	usage
fi

REPO=$1
BRANCH=$2

rebase_to_ee_branch()
{
  REPODIR="repos/$1"
  RELBRANCH=$2

  echo 
  echo "==============================="
  echo "Rebase $1 branch $2-ee from branch $2"

  if [[ ! -d ${REPODIR} ]]; then
    echo "Error: $1 is not checked out"
    exit 1
  fi

  cd $REPODIR && \
 git checkout ${RELBRANCH}-ee && \
 git rebase -i ${RELBRANCH} && \
 git status && \
 git push && \
 cd ../..
}

rebase_to_ee_branch ${REPO} ${BRANCH}

