#!/bin/bash

# This script helps to clone the MayaData forked repo
# into local machine under directory named "repos". 
# This script will also setup the upstream for the 
# cloned repo to the corresponding OpenEBS repo.

usage()
{
	echo "Usage: $0 <repo name>"
	echo " Example: $0 maya"
	exit 1
}

if [ $# -ne 1 ]; then
	usage
fi

mkdir -p repos

setup_repo()
{
  REPODIR="repos/$1"
 
  rm -rf $REPODIR

  REPOURL="https://github.com/mayadata-io/$1"
  echo 
  echo "==============================="
  echo "Cloning $REPOURL into $REPODIR"
  cd repos && git clone $REPOURL && cd ..

  if [ $(echo $PWD | rev | cut -d '/' -f1 | rev) == repos ]; then
    echo "Error: $REPOURL doesn't exist."
    exit 1
  fi

  cd $REPODIR && \
 git remote add upstream https://github.com/openebs/$1 && \
 git remote set-url --push upstream no_push && \
 git remote -v && \
 cd ../..

}

setup_repo $1
exit 0
