#!/bin/bash

# This script helps to sync (rebase) enterprise branch 
# with corresponding community branch.

usage()
{
	echo "Usage: $0 <repo name> <community release branch>"
	echo " Example: $0 maya v1.10.x"
	exit 1
}

if [ $# -ne 2 ]; then
	usage
fi

REPO=$1
BRANCH=$2

setup_repo()
{
  ./setup-update-repo $1  
}

sync_upstream_branch()
{
  REPODIR="repos/$1"
  RELBRANCH=$2

  echo 
  echo "==============================="
  echo "Rebase $1 branch $2 with upstream."

  if [[ ! -d ${REPODIR} ]]; then
    setup_repo $1
  fi

  cd $REPODIR && \
 git checkout ${RELBRANCH} && \
 git fetch upstream ${RELBRANCH} && \
 git rebase upstream/${RELBRANCH} && \
 git status && \
 git push && \
 cd ../..
}

sync_upstream_branch ${REPO} ${BRANCH}

